device-management-toolkit/wsman-messages

.eslintrc.json
src/amt/AMT.ts
src/amt/amt.test.ts
src/amt/index.ts
src/amt/models.ts
src/cim/index.ts
src/cim/models.ts
src/index.ts
src/ips/IPS.ts
src/ips/index.ts
src/ips/models.ts
src/models/common.ts
src/models/index.ts
tsconfig.json

refactor: models and exports now under respective calls AMT, IPS, CIM

---

README.md
codecov.yml
tsconfig.json

ci(badges): adds badges

---

.github/workflows/node.js.yml

ci(workflow): optimizes node CI

---

.github/workflows/node.js.yml
.github/workflows/release.yml
.releaserc.json
package-lock.json
package.json

adds semantic-release to CI flows

ci(semantic-release): adds automation for releasing

---

.github/workflows/release.yml

ci(semantic-release): fixes workflow name

---

.github/workflows/release.yml

ci(semantic-release): updates comment

---

src/amt/index.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/cim/index.ts
src/cim/messages.test.ts
src/cim/messages.ts
src/ips/index.ts
src/ips/messages.test.ts
src/ips/messages.ts

BREAKING CHANGE: Resolves stutter when instantiating class.  Ex. instead of `new AMT.AMT()` now is `new AMT.Messages()`, the same follows for IPS and CIM

refactor: renames AMT, CIM, IPS classes to Messages

---

package.json

build(release): set package.json private to false

---

package.json

build(release): adds publishConfig public to package.json

---

.releaserc.json

BREAKING CHANGE: imports no longer include `/dist`

ci(semantic-release): change pkgRoot to dist

---

package.json

build(package.json):  add postbuild

---

.github/workflows/release.yml

ci(release): update release to build

---

src/ips/messages.test.ts

adds unit test coverage for IPS functions

test(ips_messages): adds test coverage

---

.github/workflows/release.yml

ci: add cp step for package.json

---

src/amt/messages.test.ts
src/cim/messages.test.ts

test: adds test coverage to AMT, CIM, IPS messages.ts

---

.github/workflows/release.yml

ci(release): remove step

---

.github/workflows/release.yml

ci(release): add step

---

.github/workflows/release.yml
README.md

docs(readme): adds description, installation, and usage documentation

---

.github/workflows/release.yml

ci(release.yml): fixes rsync readme.md copy

---

README.md

docs(readme): update example variable name

---

codecov.yml

test(codecov): sets acceptable range to 99-100

---

src/amt/actions.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/methods.ts

feat(amt): adds unprovision and SetMEBXPassword methods to setup and configuration service

---

src/amt/actions.ts
src/amt/classes.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/methods.ts

feat(amt): adds AMT Authorization and Time Synchronization services

---

src/amt/messages.test.ts
src/amt/messages.ts
src/cim/models.ts

feat(amt): adds delete method to ManagementPresenceRemoteSAP

---

Jenkinsfile

ci(jenkinsfile): adds checkmarx and snyk scans

---

src/amt/actions.ts
src/amt/classes.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/methods.ts
src/amt/models.ts
src/cim/actions.ts
src/cim/messages.test.ts
src/cim/messages.ts
src/cim/models.ts
src/models/amt_models.ts
src/models/cim_models.ts

Adds delete method to cim WiFiEndpointSettings

feat(amt): adds WiFiPortConfigurationService to amt.

---

src/amt/messages.test.ts
src/amt/messages.ts

feat(general-settings): adds PUT method for AMT_GeneralSettings

---

src/amt/messages.test.ts
src/amt/messages.ts

feat(amt): add wifiportconfiguration service PUT and GET calls

---

src/amt/classes.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/models.ts
src/cim/models.ts

feat(AMT): Adds Remote Access Policy Applies to MPS

---

src/amt/messages.test.ts

feat(cira): adds MpsType set to both

---

src/amt/messages.ts

fix(amt): remove un-implemented method

---

.github/commitlint.config.js
.github/workflows/semantic.yml

ci(semantic): tweak lint settings

---

src/amt/messages.test.ts
src/amt/messages.ts

fix(ethernetportsettings): remove null properties before createBody

---

.github/workflows/node.js.yml

ci: remove node 12, add 18 to build

---

.github/workflows/node.js.yml

ci(jest): add junit report

---

.github/workflows/node.js.yml

ci: rename test output

---

src/WSMan.ts
src/amt/messages.test.ts
src/amt/messages.ts

closes [AB#12881](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/12881)

fix(amt): added new methods to delete certificates

---

src/WSMan.ts
src/amt/messages.ts
src/amt/models.ts
src/cim/messages.test.ts
src/cim/models.ts
src/ips/actions.ts
src/ips/classes.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/methods.ts
src/ips/models.ts

Adds IEEE8021xSettings calls to enable configuration of 802.1X settings in AMT

feat(ips): adds calls for configuring 802.1x

---

src/WSMan.ts
src/amt/messages.test.ts
src/amt/messages.ts

fix(enum): rename MEBX_PASSWORD to PASSWORD

---

src/amt/index.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/models.ts
src/amt/types.ts
src/cim/index.ts
src/cim/messages.ts
src/cim/models.ts
src/cim/types.ts
src/ips/index.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/models.ts
src/ips/types.ts

Added types to functions.  Improved acceptable number ranges for interface properties

fix: adds typed inputs to functions

---

src/cim/types.ts

fix(cim): add 32768 and 32769 allowed values for wifiport

---

src/amt/models.ts
src/amt/types.ts

fix(amt): update provisioning mode and set oemid optional

---

.github/workflows/issuesync.yml

ci: add issue sync to wsman-messages

---

.github/workflows/azureBoardsSync.yml

ci: add azure boards sync

---

.github/commitlint.config.js
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/node.js.yml
.github/workflows/release.yml
.github/workflows/semantic.yml
CONTRIBUTING.md

ci: update actions/checkout, update semantic PR

---

.github/workflows/node.js.yml

ci: add manual dispatch for nodejs.yml

---

src/amt/messages.test.ts
src/amt/messages.ts

fix(amt): remove selector check from wifiPortConfigurationService PUT

---

src/amt/classes.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/models.ts
src/amt/types.ts
src/cim/classes.ts
src/cim/messages.test.ts
src/cim/messages.ts
src/ips/classes.ts
src/ips/messages.test.ts
src/ips/messages.ts

feat: add 802.1x support to amt, cim, ips

---

src/amt/messages.test.ts
src/amt/messages.ts

refactor(amt): rename amtSwitch to switch

---

src/amt/types.ts
src/cim/types.ts
src/ips/types.ts

docs: add value map type descriptions to amt, cim, ips

---

src/amt/messages.test.ts
src/amt/messages.ts

fix(amt): handles when detection strings is not array

---

src/WSMan.ts
src/amt/actions.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/methods.ts
src/cim/messages.test.ts
src/cim/messages.ts
src/cim/models.ts
src/ips/messages.test.ts
src/ips/messages.ts

adding GET, ENUMERATE, PULL methods to all calls.  
BREAKING CHANGE: adds enumerationContext as the first parameter to all calls

feat: adds GET, ENUMERATE, PULL methods to all calls

---

src/amt/messages.ts
src/cim/messages.ts
src/ips/messages.ts

implements inferring properties from input names across all functions

refactor:  update to infer properties from inputs

---

.github/workflows/scorecard.yml

ci: add repo_token to scorecard.yaml

---

.github/workflows/azureBoardsSync.yml
.github/workflows/projectsSync.yml
.github/workflows/semantic.yml

ci: apply security best practices

---

.github/workflows/changelog.yml

ci: fixed changelog build

---

package-lock.json

build(deps): Bump http-cache-semantics to 4.1.1

---

package-lock.json
package.json

fix: update package.json version

---

src/ips/messages.test.ts
src/ips/messages.ts
src/ips/methods.ts

fix(ips): updates SetCertificates input types to string

---

src/WSMan.ts
src/amt/actions.ts
src/amt/classes.ts
src/amt/index.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/amt/methods.ts
src/amt/models.ts
src/amt/types.ts
src/cim/models.ts

feat(amt): add support for user account management

---

src/WSMan.ts
src/amt/messages.test.ts
src/amt/messages.ts
src/cim/classes.ts
src/cim/models.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/wsman.test.ts

feat(amt): add 802.1x configuration support to AddWiFiSettings

---

src/amt/actions.ts
src/amt/messages.test.ts
src/amt/messages.ts

feat(amt): adds AddKey call to PublicKeyManagementService

---

src/WSMan.ts
src/amt/messages.ts

fix: resolves issue in protectedPut default parameter

---

src/WSMan.ts
src/ips/messages.test.ts

fix: handle empty data in protectedPut

---

src/cim/messages.test.ts
src/cim/messages.ts

feat(cim): enables clearing BootConfigSetting

---

.github/workflows/release.yml

ci: update node version to 18

---

CHANGELOG.md
package-lock.json
package.json

chore: update build tasks, package.json and changelo

---

.github/workflows/scorecard.yml

ci: remove branch-protection check for scorecard

---

README.md

docs: update badge style

---

.github/workflows/node.js.yml

ci: remove node 14

---

.releaserc.json

ci: updated semantic release

---

.github/workflows/projectsSync.yml

build: change project to sync issues to

---

.github/workflows/semantic.yml

ci: add top level permissions to semantic.yml

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/node.js.yml
.github/workflows/scorecard.yml

ci: add top level permissions to nodejs and format yaml

---

.github/workflows/release.yml

ci: fix release permissions

---

.github/workflows/node.js.yml

build: node version updated

---

src/ips/actions.ts
src/ips/classes.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/methods.ts
src/ips/models.ts
src/ips/types.ts

- [x ] Unit Tests have been added for new changes
- [x ] All commented code has been removed
It adds PowerManagementService for IPS and the message for the RequestOSPowerSavingStateChange method.
AMT Reference is here:
https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/HTMLDocuments/WS-Management_Class_Reference/IPS_PowerManagementService.htm
No PR from other project.

feat(ips): add RequestOSPowerSavingStateChange in PowerManagementService

---

src/ips/models.ts
src/ips/types.ts

fix: updates the states for Power Management Service

---

.github/workflows/release.yml
package.alt.json

ci: attempt to publish to new organization

---

.snyk

fix: test patch release with device-management-toolkit

---

.github/workflows/release.yml

fix: address ci file name issue

---

.github/workflows/release.yml

ci: update semantic release version

---

.github/workflows/release.yml

ci: fix env var for auth token

---

README.md

fix: update readme for new name

---

package-lock.json
package.json

build(deps-dev): Bump jest and @types/jest

---

.github/workflows/release.yml
.releaserc.json
CHANGELOG.md
src/cim/classes.ts
src/cim/messages.test.ts
src/cim/messages.ts
src/cim/types.ts
src/ips/actions.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/models.ts
src/ips/types.ts

feat(cim): add credential context and concrete dependency interfaces

---

CHANGELOG.md
src/ips/classes.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/models.ts

feat(ips): add screen and redirection setting data

---

src/ips/actions.ts
src/ips/classes.ts
src/ips/messages.test.ts
src/ips/messages.ts
src/ips/methods.ts

feat(ips): adds HTTP Proxy Access Point
